services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hr_analytics
    ports:
      - "5433:5432"
    volumes:
      - ./schema/raw_tables.sql:/docker-entrypoint-initdb.d/01_raw_tables.sql
      - ./data/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - ./etl/01_dedup.sql:/docker-entrypoint-initdb.d/03_dedup.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "hr_analytics"]
      interval: 5s
      retries: 5